Improve production-to-staging sync
newamericafoundation/newamerica-cms pull request #1558
Opened 2020-09-24 21:46 UTC by chigby

This PR improves (or attempts to improve) the `sync-staging-from-production` fabric task by improving performance (the time it takes the command to run overall) and improved feedback to the user. Specifically:

1. Printing what media directories are being synced. These commands can take a long time so we should at least see a message stating so.
2. Restricted the number of files being synced by only syncing documents and original images. This should make it not take as long.
3. Use `aws s3 sync --size-only` to reduce the number of operations needed per file to be synced, which I think might improve performance (though I have not measured this). This option makes file comparisons based on size only, rather than a hash of the file's contents.

### Other notes

* Fixed #1552 
* I'm not sure S3 replica rules are what we want, it looks like these are for creating a system to automatically and immediately copy data from one S3 bucket to another, rather than doing so on-demand. I feel like having files automatically replicated to staging might cause problems?

2020-09-29 14:07 UTC, jacobtoppm requested changes
Generally looks great! Just a couple of minor suggestions

2020-09-29 14:07 UTC, jacobtoppm commented on fabfile.py
> +    delete_staging_renditions(c)
As this is a separate step, maybe we could stick another print in there, just to give some more feedback as to what's going on?

2020-09-29 15:27 UTC, nmorduch requested changes
- [ ] The original images are synced, but there aren't any new renditions in the bucket
  - [ ] I also think it might make sense to delete existing renditions from the bucket, but that seems like not really a big deal
- [ ] Let's add a `sync_develop_from_production` (fine with me if it's a copy-pasted duplicate tbh, for time efficiency)

2020-09-29 15:27 UTC, nmorduch commented on fabfile.py
> +            print('Syncing media folder `{}` (this may take a while).'.format(folder))
Can we add to "this may take a while" a "you'll need to keep your computer awake and connected" (assuming that you do need to)

2020-09-30 14:57 UTC, nmorduch commented on fabfile.py
> +        'heroku pg:psql --app {app} -c "DELETE FROM wagtailimages_rendition;"'.format(
@chigby just figured out that this should be deleting `home_customrendition` and should be for `delete_local_renditions` as well

2020-10-01 16:51 UTC, chigby commented
All right, I _think_ I've taken care of all the great suggestions offered here, plus the problem with the image renditions deleting from the wrong table. Should be ready to re-review.

2020-10-06 12:59 UTC, jacobtoppm reviewed
Unfortunately I don't have access to staging, so had to test this by changing the staging app name to na-develop. However, I ran into two issues doing this:
- It asked for confirmation by entering the app name, but submitted the app name after entering just one character. To get around this, I needed to copy and paste the app name.
- After "Copying... done" I got no further feedback and no continuation despite leaving for about 45 minutes. It doesn't seem to move onto the bucket syncing task. Potentially this is related to my permissions or the fact I'm doing this with "develop" rather than staging - have you encountered this before?

2020-10-06 13:23 UTC, nmorduch commented
I'm having both of the same problems as @jacobtoppm

2020-10-07 17:46 UTC, merged