Search content type
newamericafoundation/newamerica-cms pull request #1561
Opened 2020-09-29 11:59 UTC by jacobtoppm

Addresses https://github.com/newamericafoundation/newamerica-cms/issues/1530

- Display content type even if no program is found for publication listing cards, including search
- Find the program even for non Posts and for models linked to Program via tree structure rather than `parent_programs`
- Look for story image via `getattr` to find story images on non Posts

However, some page types still don't have a story image, and I wasn't sure if this was something you wanted to add as part of this, so not all pages will show images in search.

2020-09-29 12:40 UTC, kaedroho requested changes

2020-09-29 12:40 UTC, kaedroho commented on home/models.py
> +        context['program'] = self.program
Looks like `context['program']` is already being set in `super().get_context(request)`

2020-09-29 12:40 UTC, kaedroho commented on home/models.py
> +        context['program'] = self.program
As above, but you might need to remove the params in `super()` first to make it work

2020-09-29 12:40 UTC, kaedroho commented on home/models.py
> +        return self.get_parent().get_parent().specific
Would it be possible to replace this with something like: ``Program.objects.ancestor_of(self).get()``?

2020-09-29 12:40 UTC, kaedroho commented on newamericadotorg/api/search/serializers.py
> +        data['story_image'] = generate_image_url(obj.story_image, 'max-300x240') if getattr(obj, 'story_image', None) else None
I think it would be better if we could create some subclasses of this serializer for more specific types, but this is fine for now!

2020-09-29 13:29 UTC, jacobtoppm commented on home/models.py
> +        context['program'] = self.program
Good point, thanks!

2020-09-29 13:30 UTC, jacobtoppm commented on home/models.py
> +        return self.get_parent().get_parent().specific
Yes, but it needs to include subprograms, so I've used `AbstractProgram` instead - changed in latest commit.

2020-09-29 13:33 UTC, jacobtoppm commented on newamericadotorg/api/search/serializers.py
> +        data['story_image'] = generate_image_url(obj.story_image, 'max-300x240') if getattr(obj, 'story_image', None) else None
I definitely agree! It was more a question of scope for now, since I'd need to familiarise myself more with all the different types in use and which would require a more specific serialiser, but it's definitely the way to go

2020-09-29 13:40 UTC, kaedroho approved these changes

2020-10-01 19:11 UTC, nmorduch commented
Merged in f8afaa229e8168c636adc386410a012f99d19f0d (see #1563)

2020-10-01 19:11 UTC, closed without merging