Search result groups
newamericafoundation/newamerica-cms pull request #1575
Opened 2020-10-28 19:47 UTC by chigby

Groups search results into groups by content type on the search result page

2020-10-28 20:46 UTC, nmorduch requested changes
I'm running into a problem where, because this categorizes whatever comes in on a given page of search results, the first page has a lot of programs and no people, and the second page has a lot of people. I probably described unclearly what I was looking for, which was that it should have these 5 sections, and then under each section we should return the first x results if that section has any results at all (which was why I was imagining doing it on the backend, since that's where the pagination is). I'll update the issue with a mockup that gives a sense of how many of each type I'm looking to see (since i think it will be different for different types) along with any ordering we want within the category (which, to be fair, is just now occurring to me as being desirable).

2020-10-28 21:11 UTC, nmorduch commented on newamericadotorg/assets/react/home-panels/pages/Search.js
> +  if (type == "article" || type == "blogpost" || type == "book" || type == "event" || type == "issueortopic" || type == "podcast" || type == "policypaper" || type == "pressrelase" || type == "quoted"
Looks like events are going into this category so not making it to the "events" category, and "issueortopic" here should go into "other pages"

2020-10-30 21:17 UTC, chigby commented
@nmorduch Updated this PR to be more in line with what you're describing. The search page now separately searches each of the buckets and returns separately-paginated result buckets.

2020-11-16 15:05 UTC, chigby commented
Further updated the PR to reduce the number of results per page on each bucket to 6. Also made it customizable per-bucket.

2020-11-16 23:58 UTC, nmorduch commented
@chigby can you review my commit? and this should be deployed to the dev server soon

2020-11-17 15:46 UTC, nmorduch approved these changes

2020-11-17 15:47 UTC, merged