P2 Surveys and Insights.
newamericafoundation/newamerica-cms pull request #1585
Opened 2021-01-05 19:13 UTC by LeeMellon

2021-01-05 22:41 UTC, nmorduch requested changes
I'd say I've barely scratched the surface of this review, but I'm putting in the comments that I have now so that you can get started on changes.

2021-01-05 22:41 UTC, nmorduch commented on newamericadotorg/assets/react/report/components/Body.js
> -      citeEl: null
For all files with formatting changes, please remove line changes that are just formatting (or at least add PR comments noting which lines contain actual changes that need review).

2021-01-05 22:41 UTC, nmorduch commented on newamericadotorg/assets/react/surveys-homepage/components/AboutTab.js
> +      Know of a survey report that should be added to our list?
I'm assuming this is just temporary, but this will need to be editable in the admin rather than hard-coded (and the other text on the page really should be as well).

2021-01-05 22:41 UTC, nmorduch commented on newamericadotorg/assets/react/surveys-homepage/components/BasicHeader.js
> +          <a href="/education-policy">Education Policy</a>
I'm again assuming this was temporary, but this needs to be pulling the parent programmatically.

2021-01-05 22:41 UTC, nmorduch commented on newamericadotorg/assets/react/surveys-homepage/components/BasicHeader.js
> +          {data.title || 'HigherEd Polling Dashboard'}
I don't think you should need default text here since Pages always have titles (but if there is default text, it should not be specific to this project)

2021-01-05 22:41 UTC, nmorduch commented on newamericadotorg/assets/react/surveys-homepage/components/AboutTab.js
> +        body={survey_home_page.about}
Considering that this and other fields referenced on this page are not required, there should be some if statements so that we would never show the heading on one of these sections without there being any content.

2021-01-05 22:41 UTC, nmorduch commented on newamericadotorg/assets/react/surveys-homepage/components/AboutTab.js
> +      <Body
Nitpicky, feel free to ignore: I'm not sure `Body` is the name that makes the most sense here, since we associate the word "body" with things like the `<body>` tag, which is a singular piece of content very unlike this. I might consider something like `AboutTabSection` (not an amazing name, to be fair, but a little more specific)

2021-01-05 22:41 UTC, nmorduch commented on newamericadotorg/assets/react/surveys-homepage/components/CheckboxGroup.scss
> +  &__title {
This is an unexpectedly small click target heightwise, and especially is too small on mobile. I think I would probably find the easiest fix for this to be putting the `padding: 24px 0;` from line 11 on this element instead and removing this element's margin, then adding 24px of spacing to the bottom of `.checkbox-group__options`.

2021-01-05 22:56 UTC, LeeMellon commented on creds.json
> +{
Yes. I can provide you the keys (this links to a copy of the google sheet) or a link to the instructions for how to link it to the original.

2021-01-06 16:17 UTC, biggiep2 commented on newamericadotorg/assets/react/report/components/Body.js
> -      citeEl: null
Will do. You can disregard this file.

2021-01-06 16:18 UTC, biggiep2 commented on newamericadotorg/assets/react/report/index.js
> -          <h3 className="margin-top-0 margin-bottom-25">Acknowledgments</h3>
Disregard this file.

2021-01-06 16:21 UTC, biggiep2 commented on newamericadotorg/assets/react/surveys-homepage/components/AboutTab.js
> +      <Body
I replicated the naming of the Body component in Reports and my thinking is that in the future, if one wanted to use this component elsewhere, the name would be generic and descriptive enough to make sense.

2021-01-06 17:22 UTC, biggiep2 commented on newamericadotorg/assets/scss/_mixins.scss
> +  large-desktop: 1200px,
disregard this file; only formatting changes.

2021-01-06 17:26 UTC, biggiep2 commented on newamericadotorg/templates/components/card_list.html
> +      <div class="card__text__authors margin-top-5 margin-bottom-0">
Formatting changes

2021-01-06 17:39 UTC, nmorduch commented on newamericadotorg/assets/react/surveys-homepage/components/AboutTab.js
> +      <Body
Makes sense! Thanks for explaining :)

2021-01-06 17:58 UTC, biggiep2 commented on newamericadotorg/assets/react/surveys-homepage/components/BasicHeader.js
> +          {data.title || 'HigherEd Polling Dashboard'}
Removed

2021-01-06 17:58 UTC, biggiep2 commented on newamericadotorg/assets/react/surveys-homepage/components/AboutTab.js
> +        body={survey_home_page.about}
Added conditionals, good catch.

2021-01-06 17:58 UTC, biggiep2 commented on newamericadotorg/assets/react/surveys-homepage/components/CheckboxGroup.scss
> +  &__title {
Updated

2021-01-06 18:12 UTC, nmorduch commented on newamericadotorg/assets/react/surveys-homepage/components/SurveysTab.js
> +                description="Know of a survey report that should be added to our list?"
This all needs to be editable in the admin, especially the email address.

2021-01-06 18:19 UTC, LeeMellon commented on creds.json
> +{
Can't add a comment as it's a json file, but have renamed and added a comment in the migration file.

2021-01-06 19:05 UTC, nmorduch requested changes
The main change to make is to make the survey home page a sibling of subprogram, not a kind of subprogram. Basically, the survey stuff should all be its own app and as much as possible not affect other code.

2021-01-06 19:12 UTC, biggiep2 commented on newamericadotorg/assets/react/report/components/Body.js
> -      citeEl: null
Added a comma. This entire file can be ignored as its just formatting changes. Sorry, I thought I left that comment on this file.

2021-01-07 14:45 UTC, biggiep2 commented on newamericadotorg/assets/react/components/CtaCard.js
> +import './CtaCard.scss';
@LeeMellon This has been addressed in the forked PR.

2021-01-07 14:45 UTC, biggiep2 commented on newamericadotorg/assets/react/components/CtaCard.js
> +const CtaCArd = (props) => {
@LeeMellon This has been addressed in the forked PR.

2021-01-07 14:45 UTC, biggiep2 commented on newamericadotorg/assets/react/components/Tab.js
> +import React from 'react';
@LeeMellon This has been addressed in the forked PR.

2021-01-07 14:45 UTC, biggiep2 commented on newamericadotorg/assets/react/components/Tabs.js
> +import './Tabs.scss';
@LeeMellon This has been addressed in the forked PR.

2021-01-07 14:45 UTC, biggiep2 commented on newamericadotorg/assets/react/report/components/Body.scss
> +.report--polling-dashboard {
@LeeMellon This has been addressed in the forked PR.

2021-01-08 15:59 UTC, nmorduch commented on newamericadotorg/assets/react/surveys-homepage/components/BasicHeader.js
> +          <a href="/education-policy">Education Policy</a>
Is there a fix for this in the works? This needs to be changed.

2021-01-25 20:33 UTC, closed without merging