Brief pages
newamericafoundation/newamerica-cms pull request #1647
Opened 2021-04-22 16:37 UTC by chigby

Refs #1637

2021-04-27 19:26 UTC, nmorduch requested changes
My changes to the models files are nitpicky, just was copying from a different app's models.

To do:
- rebase off `main` (has a conflict in the imports so i'm leaving it for you. and then tests will pass)
- update things we're counting for word limit (see line comment)
- maybe make it have just one migration instead of both of these, but i don't know how much i care

2021-04-27 19:26 UTC, nmorduch commented on brief/models.py
> +        countable_block_types = {'paragraph', 'introduction', 'heading'}
We should also count: 
- Resource kit description
- Table content I guess?
- Everything we're already counting, but as children of a Panel

2021-04-28 16:39 UTC, nmorduch commented
Actually, how about merging #1650 into this branch, and then add the brief publishing permissions to this branch after that?

2021-04-29 19:24 UTC, nmorduch requested changes
See line comment

2021-04-29 19:24 UTC, nmorduch commented on brief/models.py
> +            for block_type, data in block.value['resources'].stream_data:
I'm getting:
> **Exception Type:** ValueError
> **Exception Value:** too many values to unpack (expected 2)
> **Exception Location:** /vagrant/brief/models.py in word_count_body_block, line 22

Also, I don't really need to count all the things in the resources. I would just keep lines 20 and 21 I think

2021-04-29 19:32 UTC, nmorduch commented on brief/wagtail_hooks.py
> +                item for item in menu_items if item.name != 'action-publish'
I didn't catch this when testing reports, but my limited-permissions user can publish a new report or brief, just can publish edits to an existing one.

2021-04-29 19:36 UTC, chigby commented on brief/wagtail_hooks.py
> +                item for item in menu_items if item.name != 'action-publish'
It's possible you need to restart your wagtail server locally. These hooks do not take effect except at the time wagtail starts up.

2021-04-29 19:38 UTC, nmorduch commented on brief/wagtail_hooks.py
> +                item for item in menu_items if item.name != 'action-publish'
Didn't fix it :/ Can still make new ones. (Can't edit existing ones! Typo above was unclear)

2021-04-29 19:43 UTC, nmorduch commented
Word count situation is fixed!

2021-04-29 19:55 UTC, chigby commented on brief/wagtail_hooks.py
> +                item for item in menu_items if item.name != 'action-publish'
I think I misread your comment earlier. Just pushed a fix for limiting the permissions when creating a new report or brief.

2021-04-29 20:08 UTC, nmorduch commented on brief/wagtail_hooks.py
> +                item for item in menu_items if item.name != 'action-publish'
Prob misread it because i'd had miswritten it 

Also this is fixed now!

2021-04-29 20:10 UTC, nmorduch approved these changes
This is great! Going to put this on the dev server so other people can see how great it is :)

2021-04-29 20:29 UTC, nmorduch requested changes
Wait a minute you lost my commits when you rebased this :p

2021-04-29 20:31 UTC, nmorduch commented
These two, of which the first is actually important:
https://github.com/newamericafoundation/newamerica-cms/commit/5c3e00c46d3c3e066967b706b15f0ad42f8e06c5
https://github.com/newamericafoundation/newamerica-cms/commit/0af73fe85be25880cb19a3a22041b48c62376a52

2021-04-29 20:35 UTC, nmorduch commented
for my review dismissal, should say: "added changes"

2021-04-29 21:38 UTC, nmorduch submitted a review, later dismissed
Cameron says he approves of my changes. This is currently in testing on the dev server.

2021-04-29 21:43 UTC, nmorduch commented
# Notes re testing on the dev server

## What I’ve set up in the admin

- I set it so “Moderators” can publish Briefs and Reports. This is in the settings menu, on the new “Publication permissions” page. We could also set those to no groups, and then it would only be “Administrators” who could publish reports & briefs.
- I made a test user who has “Editor” but not “Moderator” permissions. That user should not be able to publish any reports or briefs.
- I also made a workflow for moderator approval of reports and briefs in Asset Building, and reports in BLL just to show that it could be one workflow covering multiple programs.

### What will be different in production

- The workflow will need to apply to every program’s reports, and we’ll need to add their briefs homepages as they start having briefs homepages. (I don’t see a reason to a briefs homepage before a given program starts publishing briefs.) Fwiw, if we don’t add their reports/briefs to the workflow, they can still save drafts, they just don’t have a built-in way to submit them for moderation.
- We’ll need to make new permission groups for people who currently have admin permissions and need some permissions that they can’t get with the basic program permissions, but don’t need all the permissions. We should prob warn them when or before we do this.

## Testing

- https://na-develop.herokuapp.com/briefs/ you can filter for briefs, and the one there has two attachments.
- You can also see that brief here https://na-develop.herokuapp.com/asset-building/publications/
- Briefs are capped at 3000 words. We check some types of text and not others, but an approximate cap should be fine for our purposes. Try publishing something that’s too long, and see that the error says how many counted words you have.
- As the test user, you should not be able to publish new reports or briefs, nor edit existing ones
- Try out the moderation workflow. I would do this by having a private/incognito window where I’m logged in as the test user and submit a report or brief for moderation, then approve/reject from my regular account, and switch back to see what feels like for a user to get a page approved or rejected.

2021-04-30 14:24 UTC, nmorduch commented
Let's change this to 5k words also

2021-04-30 14:43 UTC, nmorduch approved these changes
@chigby approves latest commit

2021-05-10 19:56 UTC, merged