Headless preview
newamericafoundation/newamerica-cms pull request #1653
Opened 2021-04-30 20:56 UTC by chigby

Fixes #1635 

So far:

1. Only applies to reports
2. Uses a hard-coded "localhost" URL. This is what the docs say to do, but it means it probably won't work outside of a local dev environment. There's probably a way around this, like setting up specific URLs for each of our environments, but it is not done yet.

2021-05-03 17:38 UTC, nmorduch commented
>     2. Uses a hard-coded "localhost" URL. This is what the docs say to do, but it means it probably won't work outside of a local dev environment. There's probably a way around this, like setting up specific URLs for each of our environments, but it is not done yet.
We should be able to set a setting on Heroku for each environment, yeah?

2021-05-21 15:52 UTC, nmorduch requested changes
I'm getting errors related to using an iframe :/
@chigby noted this is mentioned in https://github.com/torchbox/wagtail-headless-preview/issues/15

2021-05-21 16:31 UTC, nmorduch requested changes
This is working for the landing page, but does not then work for the individual pages of the reports. We prob have to change the links in the nav not to be full urls, at least for the preview, and make it so that the routes then work.

2021-05-21 16:31 UTC, nmorduch commented on newamericadotorg/assets/react/report/index.js
> +          <Route
Should we delete the route above this? I think it might be to make things less look broken when preview doesn't work.

2021-05-21 19:02 UTC, nmorduch approved these changes
This looks great! You'll need to resolve the conflicts, and we should make a (lower priority) ticket for about page previews since this only fixes the preview for report pages

2021-05-21 19:08 UTC, chigby commented
Agree re: about pages. The main reason I didn't roll that into this ticket is I wasn't sure exactly if this technique would work or not.

2021-05-24 15:04 UTC, nmorduch approved these changes

2021-05-26 21:02 UTC, merged