Subscribe page models
newamericafoundation/newamerica-cms pull request #1792
Opened 2023-07-14 19:02 UTC by chigby

This PR:

1. Adds new models for Subscribe Pages, and Mailing List Segments 
2. Updates the `sync_campaign_monitor` command to create mailing list segments instead of `SubscriptionSegments`

2023-08-11 16:12 UTC, nmorduch requested changes

2023-08-11 16:15 UTC, nmorduch commented on newamericadotorg/api/program/serializers.py
> +    list_id = CharField()
And let's make sure the FE is still working

2023-08-11 16:19 UTC, nmorduch commented on subscribe/models.py
> +    list_id = models.TextField()
The new version shouldn't need segment_id or list_id since we don't actually use them

2023-08-11 16:19 UTC, nmorduch commented on newamericadotorg/api/program/serializers.py
> +    list_id = CharField()
so this format won't matter since we don't actually use those fields

2023-08-11 16:19 UTC, nmorduch commented on newamericadotorg/api/meta/views.py
> -            if s.alternate_title != "":
this is the part that could mess up the FE

2023-08-23 20:54 UTC, nmorduch commented on subscribe/models.py
> -        return self.segment_id
We should check that this doesn't count as it being used somewhere. And probably also check the createsend / campaign monitor api

2023-08-25 17:26 UTC, chigby commented
On the front end,, we obtain subscription info via the `/api/meta` call:

``` json
{
	"results": {
		"home_subscriptions": [
			{
				"id": 25803,
				"title": "COVID19 Daily Brief List",
				"ListID": "ac0721427fe250c9bfe10f98fa7fe725",
				"SegmentID": "COVID19 Daily Brief List"
			},
			{
				"id": 31114,
				"title": "Russia/Ukraine Newsletter",
				"ListID": "ac0721427fe250c9bfe10f98fa7fe725",
				"SegmentID": "Russia/Ukraine Newsletter"
			},
			{
				"id": 20255,
				"title": "New America - The Week Ahead",
				"ListID": "ac0721427fe250c9bfe10f98fa7fe725",
				"SegmentID": "New America - The Week Ahead"
			},
			{
				"id": 20259,
				"title": "New America Weekly",
				"ListID": "ac0721427fe250c9bfe10f98fa7fe725",
				"SegmentID": "New America Weekly",
				"alternate_title": "The Thread"
			}
		]
	}
}
```
(results slightly truncated). The data here contains the `ListID` and `SegmentID`, but my contention here is they are not being used. This data is used by the `Subscribe`/`HomeSubscribe` component:

https://github.com/newamericafoundation/newamerica-cms/blob/76dd94e64f751d93cbeffdc37f330c4f8fa62b8d/newamericadotorg/assets/react/home-panels/pages/Subscribe.js#L77-L80

which puts the subscriptions into a `List` component:

https://github.com/newamericafoundation/newamerica-cms/blob/76dd94e64f751d93cbeffdc37f330c4f8fa62b8d/newamericadotorg/assets/react/home-panels/pages/Subscribe.js#L57

Which renders the checkboxes:

https://github.com/newamericafoundation/newamerica-cms/blob/76dd94e64f751d93cbeffdc37f330c4f8fa62b8d/newamericadotorg/assets/react/program-page/components/Subscribe.js#L15-L32

Only the title is used here. The `subscriptions` state is an array of titles which are toggled on and off via the checkboxes and ultimately sent to the subscribe API view:

https://github.com/newamericafoundation/newamerica-cms/blob/76dd94e64f751d93cbeffdc37f330c4f8fa62b8d/newamericadotorg/api/subscribe/views.py#L42-L44

The view converts this list of titles into an array of custom fields of the form `{"key": "subscriptions", "value": "<<title>>"}`

This is then, finally, sent to campaign monitor:

https://github.com/newamericafoundation/newamerica-cms/blob/76dd94e64f751d93cbeffdc37f330c4f8fa62b8d/subscribe/campaign_monitor.py#L30-L57

Which uses the custom fields but pulls the `LIST_ID` value from the Django settings.

I added all these code snippets to help me understand what I believe to be the full process of subscribing, but what this says to me is I don't think we need the `ListID` field on the individual mailing list segments. (The snippets are from this PR's branch but the front end code is the same as on `main` and the backend code does not differ in its handling of the subscription data, but feel free to compare).

2023-10-06 14:46 UTC, nmorduch requested changes
- className in Subscribe.js
- org-wide not working
- invisible recaptcha thinks we're all 🤖

2023-10-06 14:46 UTC, nmorduch commented on newamericadotorg/assets/react/program-page/components/Subscribe.js
> +              <p class="recaptcha-notice">
Needs `className`

2023-10-06 15:23 UTC, nmorduch commented
additionally:

- i still need to do a design pass
- let's make a new name for the new secret key so that we can add it to heroku ahead of time without breaking the old recaptcha setup
- check subscriptions.length not subscriptions.size lol

For a third PR
- remove old models
- remove management command

(for anyone reading this, we are also on zoom while this review is happening and that is why the comments are just lists of action items)

2023-10-13 19:49 UTC, nmorduch approved these changes
Waiting on part 1 to merge though

2023-10-13 22:29 UTC, nmorduch approved these changes

2023-10-13 22:37 UTC, merged