Subscription Models, Part 1
newamericafoundation/newamerica-cms pull request #1808
Opened 2023-09-08 19:16 UTC by chigby

This pull request spins off the preliminary database setup from https://github.com/newamericafoundation/newamerica-cms/pull/1792 into its own branch. The purpose of this is to create new snippet models and page types that can be populated with the `make_subscribe_pages` command but won't affect the functionality of the site. This way we can set up the data beforehand and deploy the site changes in another release at a later date.

2023-09-08 20:24 UTC, nmorduch commented on home/models.py
> +    parent_page_types = [
Also needs to be able to go under the Thread homepage

2023-09-15 15:30 UTC, chigby commented on home/models.py
> +    parent_page_types = [
Added this!

2023-09-15 16:48 UTC, nmorduch requested changes
Working great! One last change: Let's have all the new segments on the subscribe pages checked by default.

2023-09-15 17:21 UTC, nmorduch approved these changes
Perfect. Will wait to merge until the other is ready.

2023-10-13 20:33 UTC, merged