Add management command to tag posts into a given program
newamericafoundation/newamerica-cms pull request #1819
Opened 2023-11-03 20:29 UTC by chigby

Management command that takes 2 slug arguments (and an optional `commit` flag) and:

1. Looks for a program, subprogram, or issue/topic with the `from` slug
2. Looks for a program with the `to` slug
3. If both are found, adds a relationship between all posts associated with the first program/subprogram/topic and the second program.

By default, only provides counts but does not alter the database. Only make changes if `--commit` is given.

Usage example:

```
docker compose exec web ./manage.py retag_program_posts --from global-assets-project --to the-alley
```

```
docker compose exec web ./manage.py retag_program_posts --from federal-student-loan-costs --to education-policy --commit
```

2023-11-17 15:31 UTC, nmorduch requested changes
- [ ] use id instead of slug bc slug can (and will) not be unique
- [ ] change to: under page a, untag all page b from all Posts, then run save on all Posts

2023-11-17 22:23 UTC, chigby commented
Updated the management command and the description of it in the description of this PR.

2023-12-01 20:54 UTC, nmorduch approved these changes

2023-12-01 22:02 UTC, nmorduch approved these changes

2023-12-01 22:03 UTC, merged