Draft: Replace Campaign Monitor with Mailchimp
newamericafoundation/newamerica-cms pull request #1875
Opened 2024-09-05 08:10 UTC by tomusher

This changes the mailing list subscription integration from Campaign Monitor to Mailchimp.

Configuration is through three new environment variables:

- `MAILCHIMP_HOST` - the API domain for the instance of Mailchimp used by the organiz€ation (`us22.api.mailchimp.com`)
- `MAILCHIMP_LIST_ID` - the ID of the audience to add subscribers to
- `MAILCHIMP_API_KEY` - API key for Mailchimp API access

`MailingListSegments` are now populated from tags on the configured list. Where tags have the same name as Campaign Monitor segments, they will be kept, so all existing subscription pages will keep working.

Job Title/Organization fields have been removed from the subscription form as requested, as these are not collected in Mailchimp.

Using a subscription form creates/updates a subscriber on the configured list:

- New contacts are added
- Existing contacts have their details updated
- List selection always adds tags, it does not remove tags from existing users. For example, if a user opts in to lists A and B, and then uses another subscription form to opt in to lists A and C, they will receive emails from segments A, B and C. This is in line with existing Campaign Monitor behavior.

2024-09-05 09:14 UTC, tm-kn requested changes
Thanks @tomusher! This looks pretty good and simple. There are only one or two issues that need addressing, but left a few other thoughts for you to consider.

2024-09-05 09:14 UTC, tm-kn commented on subscribe/mailchimp.py
> +    def __init__(self, *, host, api_key):
**Suggestion:** Could raise a `ValueError` if the API key or host are missing. It will make it easier to debug configuration issues.

2024-09-05 09:37 UTC, tomusher commented on subscribe/mailchimp.py
> +        except requests.exceptions.RequestException as e:
Good catch thank you, added!

2024-09-05 09:37 UTC, tomusher commented on subscribe/mailchimp.py
> +        return hashlib.md5(email.lower().encode()).hexdigest()
Seems like a reasonable precaution to me, added

2024-09-05 09:38 UTC, tomusher commented on subscribe/mailchimp.py
> +    except MailchimpError as e:
Added logging

2024-09-05 09:40 UTC, tomusher commented on subscribe/mailchimp.py
> +        except requests.exceptions.RequestException as e:
I think for now, as there's no other monitoring in place, we might as well treat every exception equally and see which if any start appearing in Sentry - if there's a lot of timeouts for example, it may be worth increasing the timeout value.

2024-09-05 09:40 UTC, tomusher commented on subscribe/mailchimp.py
> +                **kwargs,
Great call thanks, added

2024-09-05 09:41 UTC, tomusher commented on subscribe/mailchimp.py
> +    def __init__(self, *, host, api_key):
I've added some more useful errors in `_get_client` rather than in the client class itself, as the raised errors are Django-config specific.

2024-09-09 08:24 UTC, jacobtoppm approved these changes
Marking as reviewed following @tm-kn 's review

2024-09-09 08:26 UTC, merged